// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/unit_tests/presentation/settings/cubit/settings_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:weather_app/domain/auth/use_case/sign_out_use_case.dart' as _i8;
import 'package:weather_app/domain/locale/use_case/get_selected_language_code_use_case.dart'
    as _i3;
import 'package:weather_app/domain/locale/use_case/save_language_code_use_case.dart'
    as _i5;
import 'package:weather_app/utils/error_handling/either.dart' as _i2;
import 'package:weather_app/utils/error_handling/errors/generic_error.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetSelectedLanguageCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSelectedLanguageCodeUseCase extends _i1.Mock
    implements _i3.GetSelectedLanguageCodeUseCase {
  MockGetSelectedLanguageCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#call, []),
            ),
          )
          as String);
}

/// A class which mocks [SaveLanguageCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLanguageCodeUseCase extends _i1.Mock
    implements _i5.SaveLanguageCodeUseCase {
  MockSaveLanguageCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.GenericError, void>> call(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [languageCode]),
            returnValue: _i6.Future<_i2.Either<_i7.GenericError, void>>.value(
              _FakeEither_0<_i7.GenericError, void>(
                this,
                Invocation.method(#call, [languageCode]),
              ),
            ),
          )
          as _i6.Future<_i2.Either<_i7.GenericError, void>>);
}

/// A class which mocks [SignOutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOutUseCase extends _i1.Mock implements _i8.SignOutUseCase {
  MockSignOutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Either<_i7.GenericError, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i6.Future<_i2.Either<_i7.GenericError, void>>.value(
              _FakeEither_0<_i7.GenericError, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i6.Future<_i2.Either<_i7.GenericError, void>>);
}
