name: weather_app
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.24.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  intl: 0.19.0
  intl_utils: 2.8.7
  json_serializable: 6.8.0
  json_annotation: 4.9.0
  provider: 6.1.2
  fimber_io: 0.7.0
  get_it: 7.6.6
  dio: 5.7.0
  flutter_secure_storage: 9.2.2
  injectable: 2.4.4
  collection: 1.18.0
  freezed: 2.5.7
  freezed_annotation: 2.4.4
  equatable: 2.0.5
  retrofit: 4.4.1
  go_router: 14.2.8
  mockito: 5.4.4
  hooked_bloc: 1.5.0
  flutter_hooks: 0.20.5
  flutter_svg: 2.0.10+1
  system_proxy: 0.1.0
  shared_preferences: 2.3.2
  geolocator: 13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  bloc_test: 9.1.7
  injectable_generator: 2.6.2
  retrofit_generator: 9.1.2
  build_runner: 2.4.12
 

flutter:
  uses-material-design: true
  # assets:
  # - assets/images/svg/icons/
  # - assets/images/illustrations/
  # - assets/images/illustrations/background/
  # - assets/images/illustrations/wide_background/
  # - assets/images/illustrations/connect_locksense_one/
  # - assets/images/illustrations/connect_locksense_two/
  # - assets/images/illustrations/connect_locksense_three/
  # - assets/images/illustrations/connect_locksense_four/
  # - assets/images/illustrations/P0004173/
  # - assets/images/illustrations/P0004174/
  # - assets/images/illustrations/P0004175/
  # - assets/images/illustrations/P0004176/
  # - assets/images/illustrations/P0004177/
  # - assets/images/illustrations/P0004178/
  # - assets/images/illustrations/P0004179/
  # - assets/images/illustrations/P0004180/
  # - assets/images/illustrations/P0004181/
  # - assets/images/illustrations/P0004182/
  # - assets/images/illustrations/machine_placeholder/
  
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter-Thin.ttf
    - asset: assets/fonts/Inter-ExtraLight.ttf
    - asset: assets/fonts/Inter-Light.ttf
    - asset: assets/fonts/Inter-Medium.ttf
    - asset: assets/fonts/Inter-Regular.ttf
    - asset: assets/fonts/Inter-SemiBold.ttf
    - asset: assets/fonts/Inter-Bold.ttf
    - asset: assets/fonts/Inter-ExtraBold.ttf
    - asset: assets/fonts/Inter-Black.ttf

flutter_intl:
  enabled: true
  class_name: Strings
  main_locale: en
  