// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/widget_tests/presentation/settings/settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/domain/locale/use_case/get_selected_language_code_use_case.dart'
    as _i2;
import 'package:weather_app/domain/locale/use_case/save_language_code_use_case.dart'
    as _i3;
import 'package:weather_app/domain/location/model/location_permission_status.dart'
    as _i6;
import 'package:weather_app/domain/location/use_case/check_location_permission_status_use_case.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetSelectedLanguageCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSelectedLanguageCodeUseCase extends _i1.Mock
    implements _i2.GetSelectedLanguageCodeUseCase {
  MockGetSelectedLanguageCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [SaveLanguageCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLanguageCodeUseCase extends _i1.Mock
    implements _i3.SaveLanguageCodeUseCase {
  MockSaveLanguageCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#call, [languageCode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CheckLocationPermissionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationPermissionStatusUseCase extends _i1.Mock
    implements _i5.CheckLocationPermissionStatusUseCase {
  MockCheckLocationPermissionStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.LocationPermissionStatus> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i6.LocationPermissionStatus>.value(
              _i6.LocationPermissionStatus.denied,
            ),
          )
          as _i4.Future<_i6.LocationPermissionStatus>);
}
