// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/unit_tests/domain/weather/use_case/get_current_weather_by_city_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/domain/weather/model/current_weather.dart' as _i6;
import 'package:weather_app/domain/weather/service/weather_service.dart' as _i3;
import 'package:weather_app/utils/error_handling/either.dart' as _i2;
import 'package:weather_app/utils/error_handling/errors/generic_error.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i3.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>>
  getCurrentWeather({
    required double? latitude,
    required double? longitude,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeather, [], {
              #latitude: latitude,
              #longitude: longitude,
              #languageCode: languageCode,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.GenericError, _i6.CurrentWeather>
                >.value(
                  _FakeEither_0<_i5.GenericError, _i6.CurrentWeather>(
                    this,
                    Invocation.method(#getCurrentWeather, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #languageCode: languageCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>>);

  @override
  _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>>
  getCurrentWeatherByCity({
    required String? city,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentWeatherByCity, [], {
              #city: city,
              #languageCode: languageCode,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.GenericError, _i6.CurrentWeather>
                >.value(
                  _FakeEither_0<_i5.GenericError, _i6.CurrentWeather>(
                    this,
                    Invocation.method(#getCurrentWeatherByCity, [], {
                      #city: city,
                      #languageCode: languageCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>>);
}
