// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/widget_tests/presentation/home/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:weather_app/domain/locale/use_case/get_selected_language_code_use_case.dart'
    as _i7;
import 'package:weather_app/domain/location/model/current_location.dart'
    as _i12;
import 'package:weather_app/domain/location/model/location_permission_status.dart'
    as _i10;
import 'package:weather_app/domain/location/use_case/check_location_permission_status_use_case.dart'
    as _i9;
import 'package:weather_app/domain/location/use_case/get_current_location_use_case.dart'
    as _i11;
import 'package:weather_app/domain/weather/model/current_weather.dart' as _i6;
import 'package:weather_app/domain/weather/use_case/get_current_weather_use_case.dart'
    as _i3;
import 'package:weather_app/utils/error_handling/either.dart' as _i2;
import 'package:weather_app/utils/error_handling/errors/generic_error.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetCurrentWeatherUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentWeatherUseCase extends _i1.Mock
    implements _i3.GetCurrentWeatherUseCase {
  MockGetCurrentWeatherUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>> call({
    required double? latitude,
    required double? longitude,
    required String? languageCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #latitude: latitude,
              #longitude: longitude,
              #languageCode: languageCode,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.GenericError, _i6.CurrentWeather>
                >.value(
                  _FakeEither_0<_i5.GenericError, _i6.CurrentWeather>(
                    this,
                    Invocation.method(#call, [], {
                      #latitude: latitude,
                      #longitude: longitude,
                      #languageCode: languageCode,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GenericError, _i6.CurrentWeather>>);
}

/// A class which mocks [GetSelectedLanguageCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSelectedLanguageCodeUseCase extends _i1.Mock
    implements _i7.GetSelectedLanguageCodeUseCase {
  MockGetSelectedLanguageCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#call, []),
            ),
          )
          as String);
}

/// A class which mocks [CheckLocationPermissionStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckLocationPermissionStatusUseCase extends _i1.Mock
    implements _i9.CheckLocationPermissionStatusUseCase {
  MockCheckLocationPermissionStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.GenericError, _i10.LocationPermissionStatus>>
  call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.GenericError, _i10.LocationPermissionStatus>
                >.value(
                  _FakeEither_0<
                    _i5.GenericError,
                    _i10.LocationPermissionStatus
                  >(this, Invocation.method(#call, [])),
                ),
          )
          as _i4.Future<
            _i2.Either<_i5.GenericError, _i10.LocationPermissionStatus>
          >);
}

/// A class which mocks [GetCurrentLocationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentLocationUseCase extends _i1.Mock
    implements _i11.GetCurrentLocationUseCase {
  MockGetCurrentLocationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.GenericError, _i12.CurrentLocation>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.GenericError, _i12.CurrentLocation>
                >.value(
                  _FakeEither_0<_i5.GenericError, _i12.CurrentLocation>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.GenericError, _i12.CurrentLocation>>);
}
